### ISSUE TITLE
Continuous integration broken

### ISSUE THREAD

**Issue by jonesmz** [TheOpenSpaceProgram/osp-magnum#229] opened 2023-01-04 00:54 UTC
Started with commit https://github.com/TheOpenSpaceProgram/osp-magnum/commit/3153dd4cd30161f65b41e012e0216324f4b1cc81, which was one of several commits in a PR, so one of those.

**Comment by jonesmz** [comment] 2023-01-04 01:00
```
[100%] Linking CXX executable ../Release/osp-magnum
/tmp/lto-llvm-e93005.o: In function `Magnum::Trade::MaterialAttributeData::value() const':
MaterialData.cpp:(.text._ZNK6Magnum5Trade21MaterialAttributeData5valueEv+0x31): undefined reference to `Corrade::Containers::Implementation::stringFindCharacter(char const*, unsigned long, char)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Capital-Asterisk** [comment] 2023-01-04 01:34
Duplicate of #223. I think this is likely an LTO issue

**Closed** 2023-02-06 02:27 UTC
Labels: building
