### ISSUE TITLE
Crash on Exit command while window still opened

### ISSUE THREAD

**Issue by pirogronian** [TheOpenSpaceProgram/osp-magnum#60] opened 2021-01-23 11:14 UTC
Maybe it's not a bug, not a serious one (as I presume, command line is temporary, for debugging only), but maybe is (if placed in code intended to stay longer in project). Here is output from Gnu Debugger, since Exit command. This build is debug one, bactrace output is considerable larger.
(BTW minor inconvenience - logs can interrupt typed text, as You can see).
```
exFloating origin translation!
it
Application must be closed to destroy universe.
Magnum Application closed
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ScrollInputHandle is dead
MouseMovementHandle is dead
[Thread 0x7fffe17fa640 (LWP 6682) exited]
[Thread 0x7fffe1ffb640 (LWP 6681) exited]
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
ButtonControlHandle is dead
[Thread 0x7fffe27fc640 (LWP 6680) exited]
[Thread 0x7fffe2ffd640 (LWP 6679) exited]
[Thread 0x7fffe37fe640 (LWP 6678) exited]
[Thread 0x7fffe3fff640 (LWP 6677) exited]
[Thread 0x7fffe8a5f640 (LWP 6676) exited]
[Thread 0x7ffff71ca640 (LWP 6675) exited]
corrupted size vs. prev_size

Thread 1 "osp-magnum" received signal SIGABRT, Aborted.
0x00007ffff7441615 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7441615 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff742a862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff74835e8 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff748b27a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff748c176 in unlink_chunk.constprop () from /usr/lib/libc.so.6
#5  0x00007ffff748c305 in malloc_consolidate () from /usr/lib/libc.so.6
#6  0x00007ffff748cb30 in _int_free () from /usr/lib/libc.so.6
#7  0x00005555555ec89a in Corrade::Containers::Implementation::CallDeleter<char, void (*)(char*, unsigned long)>::operator()
    (this=0x7fffffffe0a7, deleter=0x0, data=0x5555572428c0 "P\a\237UUU", size=3145728)
    at /home/ja/Public/Programs/osp-magnum/3rdparty/corrade/src/Corrade/Containers/Array.h:60
#8  0x00005555555e9bae in Corrade::Containers::Array<char, void (*)(char*, unsigned long)>::~Array (this=0x5555559e4560, 
    __in_chrg=<optimized out>) at /home/ja/Public/Programs/osp-magnum/3rdparty/corrade/src/Corrade/Containers/Array.h:392
#9  0x00005555555e693c in Magnum::Trade::ImageData<2u>::~ImageData (this=0x5555559e4520, __in_chrg=<optimized out>)
    at /home/ja/Public/Programs/osp-magnum/3rdparty/magnum/src/Magnum/Trade/ImageData.h:106
#10 0x00005555555f769e in osp::Resource<Magnum::Trade::ImageData<2u> >::~Resource (this=0x5555559e4520, 
    __in_chrg=<optimized out>) at /home/ja/Public/Programs/osp-magnum/src/osp/Resource/Resource.h:81
#11 0x00005555555f76be in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > >::~pair (this=0x5555559e4500, __in_chrg=<optimized out>)
    at /usr/include/c++/10.2.0/bits/stl_pair.h:211
#12 0x00005555555f76ea in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > (
    this=0x5555559edea8, __p=0x5555559e4500) at /usr/include/c++/10.2.0/ext/new_allocator.h:156
#13 0x00005555555f613d in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > (__a=..., __p=0x5555559e4500) at /usr/include/c++/10.2.0/bits/alloc_traits.h:531
#14 0x00005555555f478d in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > >::_M_destroy_node (this=0x5555559edea8, __p=0x5555559e44e0) at /usr/include/c++/10.2.0/bits/stl_tree.h:646
#15 0x00005555555f1dfb in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > >::_M_drop_node (
    this=0x5555559edea8, __p=0x5555559e44e0) at /usr/include/c++/10.2.0/bits/stl_tree.h:654
#16 0x00005555555ef002 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > >::_M_erase (
    this=0x5555559edea8, __x=0x5555559e44e0) at /usr/include/c++/10.2.0/bits/stl_tree.h:1921
#17 0x00005555555eefdf in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > con--Type <RET> for more, q to quit, c to continue without paging--c
st, osp::Resource<Magnum::Trade::ImageData<2u> > > >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > >::_M_erase (this=0x5555559edea8, __x=0x5555559eea90) at /usr/include/c++/10.2.0/bits/stl_tree.h:1919
#18 0x00005555555eefdf in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > >::_M_erase (this=0x5555559edea8, __x=0x5555559eda60) at /usr/include/c++/10.2.0/bits/stl_tree.h:1919
#19 0x00005555555ec91c in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > >::~_Rb_tree (this=0x5555559edea8, __in_chrg=<optimized out>) at /usr/include/c++/10.2.0/bits/stl_tree.h:991
#20 0x00005555555e9c32 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, osp::Resource<Magnum::Trade::ImageData<2u> >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Resource<Magnum::Trade::ImageData<2u> > > > >::~map (this=0x5555559edea8, __in_chrg=<optimized out>) at /usr/include/c++/10.2.0/bits/stl_map.h:302
#21 0x00005555555ec9e4 in osp::Package::GroupTypeRes<Magnum::Trade::ImageData<2u> >::~GroupTypeRes (this=0x5555559edea0, __in_chrg=<optimized out>) at /home/ja/Public/Programs/osp-magnum/src/osp/Resource/Package.h:139
#22 0x00005555555eca0c in osp::Package::GroupTypeRes<Magnum::Trade::ImageData<2u> >::~GroupTypeRes (this=0x5555559edea0, __in_chrg=<optimized out>) at /home/ja/Public/Programs/osp-magnum/src/osp/Resource/Package.h:139
#23 0x00005555555b96d6 in std::default_delete<osp::Package::GroupType>::operator() (this=0x5555559edf68, __ptr=0x5555559edea0) at /usr/include/c++/10.2.0/bits/unique_ptr.h:85
#24 0x00005555555bbe46 in std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> >::~unique_ptr (this=0x5555559edf68, __in_chrg=<optimized out>) at /usr/include/c++/10.2.0/bits/unique_ptr.h:361
#25 0x00005555555bb2b4 in std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > >::~pair (this=0x5555559edf60, __in_chrg=<optimized out>) at /usr/include/c++/10.2.0/bits/stl_pair.h:211
#26 0x00005555555bb2d4 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > > >::destroy<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > > (this=0x5555559ed440, __p=0x5555559edf60) at /usr/include/c++/10.2.0/ext/new_allocator.h:156
#27 0x00005555555ba3f7 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > > > >::destroy<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > > (__a=..., __p=0x5555559edf60) at /usr/include/c++/10.2.0/bits/alloc_traits.h:531
#28 0x00005555555b959d in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > >, std::_Select1st<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > > >::_M_destroy_node (this=0x5555559ed440, __p=0x5555559edf40) at /usr/include/c++/10.2.0/bits/stl_tree.h:646
#29 0x00005555555b86bb in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > >, std::_Select1st<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > > >::_M_drop_node (this=0x5555559ed440, __p=0x5555559edf40) at /usr/include/c++/10.2.0/bits/stl_tree.h:654
#30 0x00005555555e134e in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > >, std::_Select1st<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > > >::_M_erase (this=0x5555559ed440, __x=0x5555559edf40) at /usr/include/c++/10.2.0/bits/stl_tree.h:1921
#31 0x00005555555e1294 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > >, std::_Select1st<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > > >::~_Rb_tree (this=0x5555559ed440, __in_chrg=<optimized out>) at /usr/include/c++/10.2.0/bits/stl_tree.h:991
#32 0x00005555555e0ff0 in std::map<unsigned int, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<osp::Package::GroupType, std::default_delete<osp::Package::GroupType> > > > >::~map (this=0x5555559ed440, __in_chrg=<optimized out>) at /usr/include/c++/10.2.0/bits/stl_map.h:302
#33 0x00005555555e103c in osp::Package::~Package (this=0x5555559ed440, __in_chrg=<optimized out>) at /home/ja/Public/Programs/osp-magnum/src/osp/Resource/Package.h:93
#34 0x00005555555e105c in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package>::~pair (this=0x5555559ed420, __in_chrg=<optimized out>) at /usr/include/c++/10.2.0/bits/stl_pair.h:211
#35 0x00005555555e1088 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> > (this=0x5555559aa8c0 <g_osp>, __p=0x5555559ed420) at /usr/include/c++/10.2.0/ext/new_allocator.h:156
#36 0x00005555555e0e81 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> > (__a=..., __p=0x5555559ed420) at /usr/include/c++/10.2.0/bits/alloc_traits.h:531
#37 0x00005555555e0c23 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> > >::_M_destroy_node (this=0x5555559aa8c0 <g_osp>, __p=0x5555559ed400) at /usr/include/c++/10.2.0/bits/stl_tree.h:646
#38 0x00005555555e0839 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> > >::_M_drop_node (this=0x5555559aa8c0 <g_osp>, __p=0x5555559ed400) at /usr/include/c++/10.2.0/bits/stl_tree.h:654
#39 0x00005555556400ee in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> > >::_M_erase (this=0x5555559aa8c0 <g_osp>, __x=0x5555559ed400) at /usr/include/c++/10.2.0/bits/stl_tree.h:1921
#40 0x000055555563f48e in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> > >::~_Rb_tree (this=0x5555559aa8c0 <g_osp>, __in_chrg=<optimized out>) at /usr/include/c++/10.2.0/bits/stl_tree.h:991
#41 0x000055555563f052 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, osp::Package, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, osp::Package> > >::~map (this=0x5555559aa8c0 <g_osp>, __in_chrg=<optimized out>) at /usr/include/c++/10.2.0/bits/stl_map.h:302
#42 0x00005555556434e2 in osp::OSPApplication::~OSPApplication (this=0x5555559aa8c0 <g_osp>, __in_chrg=<optimized out>) at /home/ja/Public/Programs/osp-magnum/src/./osp/OSPApplication.h:35
#43 0x00007ffff7443db7 in __run_exit_handlers () from /usr/lib/libc.so.6
#44 0x00007ffff7443f5e in exit () from /usr/lib/libc.so.6
#45 0x00007ffff742c159 in __libc_start_main () from /usr/lib/libc.so.6
#46 0x000055555556b4ae in _start ()
```

**Comment by jonesmz** [comment] 2021-03-02 03:35
@pirogronian

If you're able to, could you try to reproduce this with the latest master branch? Quite a few changes have been made since.

**Comment by pirogronian** [comment] 2021-03-06 17:39
@jonesmz Sorry for late reply. At commit 1db5bb8edb68c860bcd7bb4682a349553035db76 there is no crash. But there is other difference: window opens automatically. Is this intentional? And command prompt ('>' character) is often still missing, which could be confusing.

**Comment by Capital-Asterisk** [comment] 2021-04-17 23:09
> @jonesmz Sorry for late reply. At commit [1db5bb8](https://github.com/TheOpenSpaceProgram/osp-magnum/commit/1db5bb8edb68c860bcd7bb4682a349553035db76) there is no crash. But there is other difference: window opens automatically. Is this intentional? And command prompt ('>' character) is often still missing, which could be confusing.

Yes, new changes have launch arguments and by default the flight scene is opened automatically. A bunch of other things get printed after the '>', and I don't think there's a simple solution to that, nor is it that important to deal with :p. Closing this issue since the main bug is already fixed.

**Closed by Capital-Asterisk** 2021-04-17 23:09 UTC
Labels: bug
